### ISSUE TITLE
"Generic은 왜 Wrapper Class만 사용한가?" 오타 제보

### ISSUE THREAD

**Issue by Hyeon9mak** [binghe819/tech-interview#1]

**Comment by binghe819** [comment]
첫 제보 감사합니다 :) :) 👍  💯  근데 어떤 부분이 오타죠?ㅋㅋㅋㅋㅋ

**Comment by Hyeon9mak** [comment]
“사용한가?” 를 사용하는가? 로 바꿀 수 있을거 같아요

**Comment by binghe819** [comment]
좋은 제보 고마워요 현구막 :)

**Comment by Hyeon9mak** [comment]
![image](https://user-images.githubusercontent.com/37354145/141610267-05394b98-ea64-453c-b616-32430a603763.png)

**Comment by binghe819** [comment]
루터에서 나 보면 커피사라하라 🤓
